// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ravgwtrcogzggmxuuzvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhdmd3dHJjb2d6Z2dteHV1enZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNjg4NzcsImV4cCI6MjA1OTY0NDg3N30.9xY0sKHNUuOBsJxIlm-ppThqal3RO_ue27-GXHG3GgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);